version: '3'
services:
  frontend:
    build: ./front
    ports:
      - '3000:80'
    environment:
      - NODE_ENV=development
    volumes:
      - ./front:/app
      - /app/node_modules

  backend:
    build: ./back
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - ./back:/app
      - /app/node_modules
    command: npm run start:dev
